### PR TITLE
PLANNER-955: Added constraint matches to ShiftView

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
@rsynek will do for this one; most of the PR's this week were UI/visual changes, and would need a human to verify them (and would require constant updating as the UI evolves)

**Comment by rsynek** [comment]
@Christopher-Chianelli thanks!

**Comment by Christopher-Chianelli** [comment]
@rsynek Tests depend on https://github.com/kiegroup/optashift-employee-rostering/pull/150, which updated the REST API (namely, ability to create a RosterState, which need to exists in order to create/get shifts) (cannot create clean state from an example tenant, since there is no method for getting all EmployeeAvaliabilities). Managed to fix the serialization issue, needed to change resteasy-jackson-provider to resteasy-jackson2-provider and register the server ObjectMapper context provider.

**Comment by Christopher-Chianelli** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
I merged this early because I couldn't get my "github UI conflict resolution changes" locally and waiting for jenkins is unreliably long. There's a compilation error but I am fixing that now.

**Pull request merged**
