### PR TITLE
PLANNER-1125: Various bug fixes

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
jenkins retest this

**Comment by Christopher-Chianelli** [comment]
jenkins retest this

**Comment by yurloc** [comment]
@Christopher-Chianelli Is this meant to fix all of the bugs described in https://issues.jboss.org/browse/PLANNER-1125? The "add foo spot, add shift for foo, then delete it -> error popup" use case is still broken.

Otherwise looks good.

**Comment by Christopher-Chianelli** [comment]
@yurloc Yes; I have tested "add foo spot, add shift for foo, then delete (the shift for foo)"; no error popup (it is handled by the new `moveAddedGridObjectToIdMap` method in `Lane`). "add foo spot, add shift for foo, then delete (the spot foo)" is suppose to be an ErrorPopup for now; that issue is https://issues.jboss.org/browse/PLANNER-1095

**Pull request merged**
