### PR TITLE
PLANNER-1128: Fixed infinite loading bug

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Logs seem to suggest parallel execution of integration tests causes this PR to fail:
```
17:45:13 [WARNING] *****************************************************************
17:45:13 [WARNING] * Your build is requesting parallel execution, but project      *
17:45:13 [WARNING] * contains the following plugin(s) that have goals not marked   *
17:45:13 [WARNING] * as @threadSafe to support parallel building.                  *
17:45:13 [WARNING] * While this /may/ work fine, please look for plugin updates    *
17:45:13 [WARNING] * and/or request plugins be made thread-safe.                   *
17:45:13 [WARNING] * If reporting an issue, report it against the plugin in        *
17:45:13 [WARNING] * question, not against maven-core                              *
17:45:13 [WARNING] *****************************************************************
17:45:13 [WARNING] The following plugins are not marked @threadSafe in Employee Rostering as a Service Webapp:
17:45:13 [WARNING] org.codehaus.cargo:cargo-maven2-plugin:1.6.5
17:45:13 [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
```

and

```
17:46:14 [WARNING] The requested profile "wildfly11" could not be activated because it does not exist.
17:46:14 [ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.6.5:start (start-container) on project optashift-employee-rostering-webapp: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly11xInstalledLocalContainer@3e343f29]: Deployable [http://localhost:8080/] failed to finish deploying within the timeout period [30000]. The Deployable state is thus unknown. -> [Help 1]
```

**Comment by Christopher-Chianelli** [comment]
`mvn clean install` works on my machine, so look like it an issue with parallel execution

**Comment by yurloc** [comment]
jenkins retest this

**Comment by yurloc** [comment]
The build failed because of the deployment timeout in cargo plugin. Should be fixed by #161.

**Pull request merged**
